[package]
name = "rsShade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.44.0"
gl33 = "0.2.1"
notify = "4.0.17"
imgui = "0.8.2"
imgui-opengl-renderer = "0.11.1"
